### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jgravois** [koopjs/koopjs.github.io#1]
I want to help w/ this!

**Comment by ngoldman** [comment]
one thing to do is to start moving things hidden in the wiki on esri/koop into markdown files in this repo that can later be turned into pages

**Comment by jgravois** [comment]
fer sure.  consider me *on it*.

**Comment by ngoldman** [comment]
@jgravois started working on an official list of providers at https://github.com/koopjs/koopjs.github.io/blob/master/doc/providers.md. Feel free to improve. Would be great to have a list of plugins too (like for data caches, other things). Also thinking about a tutorial for how to create a provider module.
