### ISSUE TITLE
fix all links pointing to Esri/koop

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koopjs.github.io#11]
Koop has moved to http://github.com/koopjs/koop! We need to update all links pointing to the old address (http://github.com/Esri/koop) in the many repos under http://github.com/koopjs.

**Comment by jgravois** [comment]
i know i've been MIA, but i can take care of this.

**Comment by ngoldman** [comment]
I think this is done.

@jgravois :raised_hands: :pray:

**Comment by jgravois** [comment]
:speedboat:
