### ISSUE TITLE
list of providers link is broken

### ISSUE THREAD

**Issue by elgelbo** [koopjs/koopjs.github.io#18]

**Comment by elgelbo** [comment]
broken link

**Comment by jgravois** [comment]
can you be a little more specific please?

when i visit http://koopjs.github.io/ and click on either of the [Providers](http://koopjs.github.io/docs/providers/) links, they both take me to: http://koopjs.github.io/docs/providers/

**Comment by tomtom92** [comment]
@elgelbo, this should be handled in #20.
