### ISSUE TITLE
Use the badge from Travis CI for build status

### ISSUE THREAD

**Issue by haoliangyu** [koopjs/koopjs.github.io#38]
The badge of build status for plugins are now from shields.io and it displays the status of the latest build, no matter from where! It can be even a PR build.

For example, the CKAN provider has a `failed` build status at the homepage

![image](https://user-images.githubusercontent.com/1726265/50359624-66ec3700-052b-11e9-9813-6fa6810b9067.png)

But if I click at the status badge, the failure is from a greenkeeper PR

![image](https://user-images.githubusercontent.com/1726265/50359671-8f743100-052b-11e9-9a8f-a333d31c9851.png)

At the same time, the build status of the master branch is green

![image](https://user-images.githubusercontent.com/1726265/50359703-a87ce200-052b-11e9-87c9-811c4452c90e.png)

This can be very misleading for the user. I would suggest to use the badge image directly from Travis CI and specify the branch to `master` for stability. It is like:

```
https://travis-ci.org/koopjs/koop-provider-ckan.svg?branch=master
```

**Comment by rgwozdz** [comment]
Looks like we can still use img.shields.io, but we have to specify the branch.  For example, the currently used CKAN provider badge is:
`![travis](https://img.shields.io/travis/koopjs/koop-provider-ckan.svg?style=flat-square)`
![travis](https://img.shields.io/travis/koopjs/koop-provider-ckan.svg?style=flat-square)

and as you noted, this is for latest build, not master.  But if you add `/master` to the url, we get last build of master:

`![travis](https://img.shields.io/travis/koopjs/koop-provider-ckan/master.svg?style=flat-square)`
![travis](https://img.shields.io/travis/koopjs/koop-provider-ckan/master.svg?style=flat-square)

**Comment by rgwozdz** [comment]
Fixed what was fixable....it turns out that some of the failing/unknown badges were the repos were not configured to do Travis builds.  I removed those badges altogether and replaced with an `NA` in hopes of reducing confusion.
