### ISSUE TITLE
make the landing page more of a landing page

### ISSUE THREAD

**Issue by chelm** [koopjs/koopjs.github.io#5]
Hey @ngoldman and @jgravois I was thinking about taking https://github.com/koopjs/koopjs.github.io/blob/master/doc/providers.md and adding it to the landing page in some fashion. Also would like to think about where some docs would go. Everything needs a home.

**Comment by jgravois** [comment]
i've been flaky so far, but now i've got some free time and i plan on taking the reigns on building out a website for koop based on doc written in markdown.
