### ISSUE TITLE
bump all packages to v1.0.0+

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koopjs.github.io#6]
See https://nodesource.com/blog/semver-tilde-and-caret, especially https://nodesource.com/blog/semver-tilde-and-caret#1-0-0-anxiety. Using 1.0.0+ versions simplifies dependency management and ensures we are really using SemVer. `^0.y.z` will always lock to that specific number, wheras `^1.y.z` will pick the highest minor and patch version without going above 1, which I think is a lot easier to deal with and what people expect.

**Comment by ngoldman** [comment]
@chelm this explains a lot re: that weirdness we were dealing with a few weeks ago. Using 1.0.0+ (and starting new modules at 1.0.0) should allow us to avoid dealing with versioning issues like that.

**Comment by ngoldman** [comment]
I updated [providers.md](https://github.com/koopjs/koopjs.github.io/blob/master/docs/providers.md), [caches.md](https://github.com/koopjs/koopjs.github.io/blob/master/docs/caches.md), & [plugins.md](https://github.com/koopjs/koopjs.github.io/blob/master/docs/plugins.md) to make it a lot easier to see version and build status for every module related to the project.

**Comment by ngoldman** [comment]
Here's everything under the koopjs org.

| version | module |
| ---: | :--- |
| [![npm](https://img.shields.io/npm/v/koop-agol.svg?style=flat-square)](https://www.npmjs.com/package/koop-agol) | [ArcGIS Online](https://github.com/koopjs/koop-agol) |
| [![npm](https://img.shields.io/npm/v/koop-github.svg?style=flat-square)](https://www.npmjs.com/package/koop-github) | [GitHub](https://github.com/koopjs/koop-github) |
| [![npm](https://img.shields.io/npm/v/koop-gist.svg?style=flat-square)](https://www.npmjs.com/package/koop-gist) | [GitHub Gist](https://github.com/koopjs/koop-gist) |
| [![npm](https://img.shields.io/npm/v/koop-socrata.svg?style=flat-square)](https://www.npmjs.com/package/koop-socrata) | [Socrata](https://github.com/koopjs/koop-socrata) |
| [![npm](https://img.shields.io/npm/v/koop-ckan.svg?style=flat-square)](https://www.npmjs.com/package/koop-ckan) | [CKAN](https://github.com/koopjs/koop-ckan) |
| [![npm](https://img.shields.io/npm/v/koop-acs.svg?style=flat-square)](https://www.npmjs.com/package/koop-acs) | [American Community Survey](https://github.com/koopjs/koop-acs) |
| [![npm](https://img.shields.io/npm/v/koop-osm.svg?style=flat-square)](https://www.npmjs.com/package/koop-osm) | [OpenStreetMap](https://github.com/koopjs/koop-osm) |
| [![npm](https://img.shields.io/npm/v/koop-geocommons.svg?style=flat-square)](https://www.npmjs.com/package/koop-geocommons) | [GeoCommons](https://github.com/koopjs/koop-geocommons) |
| [![npm](https://img.shields.io/npm/v/koop-vrbo.svg?style=flat-square)](https://www.npmjs.com/package/koop-vrbo) | [VRBO](https://github.com/koopjs/koop-vrbo) |
| [![npm](https://img.shields.io/npm/v/koop-census.svg?style=flat-square)](https://www.npmjs.com/package/koop-census) | [Census](https://github.com/koopjs/koop-census) |
| [![npm](https://img.shields.io/npm/v/koop-yelp.svg?style=flat-square)](https://www.npmjs.com/package/koop-yelp) | [Yelp](https://github.com/koopjs/koop-yelp) |
| [![npm](https://img.shields.io/npm/v/koop-pgcache.svg?style=flat-square)](https://www.npmjs.com/package/koop-pgcache) | [PostGIS](https://github.com/koopjs/koop-pgcache) |
| [![npm](https://img.shields.io/npm/v/koop-escache.svg?style=flat-square)](https://www.npmjs.com/package/koop-escache) | [ElasticSearch](https://github.com/koopjs/koop-escache) |
| [![npm](https://img.shields.io/npm/v/koop-tile-plugin.svg?style=flat-square)](https://www.npmjs.com/package/koop-tile-plugin) | [Koop Tile Plugin](https://github.com/koopjs/koop-tile-plugin) |

**Comment by dmfenton** [comment]
Shouldn't we only do this for packages we consider stable? 

E.g. Yelp is totally expiremental and ES cache is not finished.

**Comment by ngoldman** [comment]
@dmfenton Depends on your release philosophy. I would argue we should start at 1.0.0 so our version numbers actually mean something with respect to SemVer and `npm`. See https://nodesource.com/blog/semver-tilde-and-caret#recommendation-start-at-1-0-0, namely advice from two major NPM developers:

![](https://cloud.githubusercontent.com/assets/43438/3810241/73b45fe8-1c8d-11e4-88cd-869bf4ab05c2.png)

![](https://cloud.githubusercontent.com/assets/43438/3810216/1f70e172-1c8d-11e4-82c6-fabc0a944796.png)

We can (and should) mark projects that are unstable as alpha or beta (or unfinished, or experimental) in the documentation (README). If we use 1.0.0+, when we fix bugs and upgrade the modules in different ways, it will get pulled in by projects that depend on them. :smile_cat:

**Comment by ngoldman** [comment]
Focusing exclusively on officially supported modules, which are now listed in the readme (https://github.com/koopjs/koopjs.github.io/#providers).

Everything's 1.0.0 or above! yay :tada: :balloon:
